[package]
name = "mm2_tut"
version = "0.1.0"
edition.workspace = true

[dependencies]
mork            = { workspace=true }
mork-frontend   = { workspace=true }
mork-expr       = { workspace=true }
pathmap         = { workspace=true }
